// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_ActorBodysizeReactor","status":true,"description":"アクターボディサイズリアクター ver2.1.3\r\n職業、装備、スキル、ステートからボディサイズを算出します。","parameters":{"MaleAverageHeight":"170.8","FemaleAverageHeight":"158.1"}}
];
